import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/prisma';
import { generateLearningPathInTransaction } from '@/lib/learning-path/auto-generate';

/**
 * POST /api/practice/check
 *
 * 练习入口守卫 API
 *
 * 功能：
 * 1. 检查用户是否有 active 学习路径
 * 2. 如果没有路径但已完成测评（60-89分），自动生成
 * 3. 返回是否可以进入练习及跳转目标
 */
export async function POST(req: NextRequest) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: '未登录' }, { status: 401 });
    }

    const { returnTo } = await req.json();

    // 1. 检查是否已有 active 学习路径
    const existingPath = await prisma.learningPath.findFirst({
      where: { userId: session.user.id, status: 'active' },
      select: { id: true },
    });

    if (existingPath) {
      return NextResponse.json({
        success: true,
        redirectUrl: returnTo || '/practice',
        hasLearningPath: true,
        learningPathId: existingPath.id,
      });
    }

    // 2. 检查是否完成测评
    const user = await prisma.user.findUnique({
      where: { id: session.user.id },
      select: { initialAssessmentCompleted: true, initialAssessmentScore: true },
    });

    if (!user?.initialAssessmentCompleted) {
      // 未测评：返回提示或跳转诊断页
      return NextResponse.json({
        success: false,
        needsDiagnostic: true,
        redirectUrl: '/assessment/diagnostic',
        hasLearningPath: false,
        learningPathId: null,
      });
    }

    // 3. 测评已完成但无路径：检查分数是否适合自动生成
    if (user.initialAssessmentScore && 60 <= user.initialAssessmentScore && user.initialAssessmentScore < 90) {
      try {
        // 获取最新的测评记录
        const latestAssessment = await prisma.assessment.findFirst({
          where: { userId: session.user.id, type: 'initial' },
          orderBy: { completedAt: 'desc' },
          select: { id: true },
        });

        if (latestAssessment) {
          const newPathId = await generateLearningPathInTransaction(prisma, {
            userId: session.user.id,
            assessmentId: latestAssessment.id,
          });

          return NextResponse.json({
            success: true,
            redirectUrl: returnTo || '/practice',
            hasLearningPath: true,
            learningPathId: newPathId,
            autoGenerated: true,
          });
        }
      } catch (err) {
        console.error('[Practice Check] Auto-generate failed:', err);
        // 生成失败，允许进入练习（使用 UserKnowledge）
      }
    }

    // 4. 其他情况：允许进入（使用 UserKnowledge）
    return NextResponse.json({
      success: true,
      redirectUrl: returnTo || '/practice',
      hasLearningPath: false,
      learningPathId: null,
    });
  } catch (error) {
    console.error('[Practice Check] Error:', error);
    return NextResponse.json(
      { error: '检查失败' },
      { status: 500 }
    );
  }
}
